import type { Email, Label } from "@/lib/types";

const NOW = Date.now();
const HOUR = 60 * 60 * 1000;
const DAY = 24 * HOUR;

function iso(offsetMs: number): string {
  return new Date(NOW - offsetMs).toISOString();
}

export const seedLabels: Label[] = [
  { id: "lbl-work", name: "Work", color: "purple", createdAt: iso(30 * DAY), updatedAt: iso(30 * DAY) },
  { id: "lbl-personal", name: "Personal", color: "green", createdAt: iso(30 * DAY), updatedAt: iso(30 * DAY) },
  { id: "lbl-finance", name: "Finance", color: "red", createdAt: iso(30 * DAY), updatedAt: iso(30 * DAY) },
  { id: "lbl-news", name: "Newsletter", color: "amber", createdAt: iso(30 * DAY), updatedAt: iso(30 * DAY) },
  { id: "lbl-travel", name: "Travel", color: "teal", createdAt: iso(30 * DAY), updatedAt: iso(30 * DAY) },
  { id: "lbl-social", name: "Social", color: "pink", createdAt: iso(30 * DAY), updatedAt: iso(30 * DAY) },
];

const me = "you@zmail.com";

export const seedEmails: Omit<Email, "id" | "createdAt" | "updatedAt">[] = [
  {
    threadId: "t_welcome1",
    fromName: "Zmail Team",
    fromEmail: "team@zmail.com",
    toEmails: me,
    ccEmails: "",
    bccEmails: "",
    subject: "Welcome to Zmail — your inbox, upgraded",
    body:
      "<p>Hi there,</p><p>Welcome aboard! Your new Zmail inbox is ready to go. We built Zmail to be fast, distraction-free, and genuinely pleasant to use.</p><p>Here are a few things you can try right now:</p><ul><li>Press <b>Compose</b> to send your first message.</li><li>Star important emails to find them later.</li><li>Use <b>Labels</b> on the left to organize conversations.</li><li>Search anything from the top bar.</li></ul><p>Reply to this email if you have any questions — we read every one.</p><p>Cheers,<br/>The Zmail Team</p>",
    snippet: "Welcome aboard! Your new Zmail inbox is ready to go. We built Zmail to be fast, distraction-free, and genuinely pleasant to use.",
    date: iso(2 * HOUR),
    isRead: false,
    isStarred: true,
    isImportant: true,
    folder: "INBOX",
    labels: "Personal",
    hasAttachment: false,
    attachmentName: "",
  },
  {
    threadId: "t_design2",
    fromName: "Priya Sharma",
    fromEmail: "priya.sharma@northwind.design",
    toEmails: me,
    ccEmails: "mark@northwind.design",
    bccEmails: "",
    subject: "Re: Q3 product redesign — final mockups attached",
    body:
      "<p>Hi,</p><p>I've attached the final mockups for the Q3 redesign. The team has signed off on the hero section and the pricing grid. Could you give the attachment a quick look before our 3pm sync?</p><p>A couple of notes:</p><ol><li>We moved the testimonial carousel above the footer.</li><li>Primary CTA is now in the strong rose color we discussed.</li><li>Mobile breakpoint collapses the pricing grid into tabs.</li></ol><p>Let me know if anything looks off.</p><p>Best,<br/>Priya</p>",
    snippet: "I've attached the final mockups for the Q3 redesign. The team has signed off on the hero section and the pricing grid.",
    date: iso(5 * HOUR),
    isRead: false,
    isStarred: false,
    isImportant: true,
    folder: "INBOX",
    labels: "Work",
    hasAttachment: true,
    attachmentName: "q3-mockups-final.pdf",
  },
  {
    threadId: "t_invoice3",
    fromName: "Acme Billing",
    fromEmail: "billing@acme.io",
    toEmails: me,
    ccEmails: "",
    bccEmails: "",
    subject: "Your August invoice is ready (INV-20418)",
    body:
      "<p>Hello,</p><p>Your invoice for August is ready to download. A summary is below:</p><table style='border-collapse:collapse;width:100%'><tr><td style='padding:6px;border:1px solid #eee'>Plan</td><td style='padding:6px;border:1px solid #eee'>Pro Annual</td></tr><tr><td style='padding:6px;border:1px solid #eee'>Amount</td><td style='padding:6px;border:1px solid #eee'>$240.00</td></tr><tr><td style='padding:6px;border:1px solid #eee'>Due</td><td style='padding:6px;border:1px solid #eee'>Sep 15</td></tr></table><p>You can pay online from your billing dashboard. No action needed if you're on auto-pay.</p><p>Thanks for being a customer!<br/>Acme Billing</p>",
    snippet: "Your invoice for August is ready to download. Plan: Pro Annual, Amount: $240.00, Due: Sep 15.",
    date: iso(9 * HOUR),
    isRead: true,
    isStarred: false,
    isImportant: false,
    folder: "INBOX",
    labels: "Finance",
    hasAttachment: true,
    attachmentName: "invoice-INV-20418.pdf",
  },
  {
    threadId: "t_weekly4",
    fromName: "The Weekly Byte",
    fromEmail: "hello@weeklybyte.dev",
    toEmails: me,
    ccEmails: "",
    bccEmails: "",
    subject: "5 frontend patterns that aged like milk 🥛",
    body:
      "<p>Hey readers,</p><p>This week we dig into five once-popular frontend patterns that haven't stood the test of time — and what to use instead.</p><ol><li>Render-prop everything</li><li>Redux for toast notifications</li><li>Hand-rolled modals (use a library!)</li><li>CSS-in-JS runtime costs</li><li>Dropdowns without keyboard support</li></ol><p>Read the full breakdown on the blog.</p><p>— The Byte crew</p>",
    snippet: "This week we dig into five once-popular frontend patterns that haven't stood the test of time — and what to use instead.",
    date: iso(1 * DAY),
    isRead: true,
    isStarred: false,
    isImportant: false,
    folder: "INBOX",
    labels: "Newsletter",
    hasAttachment: false,
    attachmentName: "",
  },
  {
    threadId: "t_flight5",
    fromName: "SkyHigh Airlines",
    fromEmail: "noreply@skyhigh.aero",
    toEmails: me,
    ccEmails: "",
    bccEmails: "",
    subject: "Check-in is open: Flight SH204 → Cairo, Aug 28",
    body:
      "<p>Good news — online check-in for your flight to Cairo is now open.</p><p><b>Flight:</b> SH204<br/><b>From:</b> JFK Terminal 4<br/><b>To:</b> CAI Terminal 2<br/><b>Departure:</b> Aug 28, 11:25 PM<br/><b>Seat:</b> 14C (aisle)</p><p>Check in now to get your boarding pass on your phone.</p><p>Safe travels,<br/>SkyHigh Airlines</p>",
    snippet: "Good news — online check-in for your flight to Cairo is now open. Flight SH204, departure Aug 28 11:25 PM.",
    date: iso(1 * DAY + 3 * HOUR),
    isRead: true,
    isStarred: true,
    isImportant: false,
    folder: "INBOX",
    labels: "Travel",
    hasAttachment: false,
    attachmentName: "",
  },
  {
    threadId: "t_launch6",
    fromName: "Marcus Lee",
    fromEmail: "marcus@frostedlabs.io",
    toEmails: me,
    ccEmails: "ana@frostedlabs.io",
    bccEmails: "",
    subject: "Launch checklist for Thursday — can you review?",
    body:
      "<p>Hey,</p><p>Putting together the launch checklist for Thursday. Can you skim it before EOD?</p><ul><li>Landing page copy final pass</li><li>Pricing toggle default to monthly</li><li>Analytics event for signup funnel</li><li>Press kit uploaded to /press</li><li>Status page green across regions</li></ul><p>If we're good, I'll freeze the build at midnight.</p><p>— M</p>",
    snippet: "Putting together the launch checklist for Thursday. Can you skim it before EOD?",
    date: iso(1 * DAY + 6 * HOUR),
    isRead: false,
    isStarred: false,
    isImportant: true,
    folder: "INBOX",
    labels: "Work",
    hasAttachment: false,
    attachmentName: "",
  },
  {
    threadId: "t_party7",
    fromName: "Dana Whitfield",
    fromEmail: "dana.w@gmail.com",
    toEmails: me,
    ccEmails: "",
    bccEmails: "",
    subject: "BBQ at ours this Saturday? 🍔",
    body:
      "<p>Hi!</p><p>We're doing a BBQ at ours this Saturday from around 4pm. Nothing fancy — just burgers, beers, and the dog running around.</p><p>Bring a side if you like. Let me know if you can make it!</p><p>xx<br/>Dana</p>",
    snippet: "We're doing a BBQ at ours this Saturday from around 4pm. Nothing fancy — just burgers, beers, and the dog.",
    date: iso(2 * DAY),
    isRead: true,
    isStarred: false,
    isImportant: false,
    folder: "INBOX",
    labels: "Personal,Social",
    hasAttachment: false,
    attachmentName: "",
  },
  {
    threadId: "t_pr8",
    fromName: "OpenTools Weekly",
    fromEmail: "digest@opentools.weekly",
    toEmails: me,
    ccEmails: "",
    bccEmails: "",
    subject: "This week in open source: a new bundler, a fast ORM, and 4 repos to star",
    body:
      "<p>Three things caught our eye this week:</p><ul><li>A new Rust-based bundler claiming 10x cold starts</li><li>A type-safe ORM with zero config</li><li>Four repos worth starring before they blow up</li></ul><p>Full links in the web version.</p>",
    snippet: "Three things caught our eye this week: a Rust-based bundler, a type-safe ORM, and four repos to star.",
    date: iso(2 * DAY + 5 * HOUR),
    isRead: true,
    isStarred: false,
    isImportant: false,
    folder: "INBOX",
    labels: "Newsletter",
    hasAttachment: false,
    attachmentName: "",
  },
  {
    threadId: "t_meeting9",
    fromName: "Sofia Almeida",
    fromEmail: "sofia@northwind.design",
    toEmails: me,
    ccEmails: "",
    bccEmails: "",
    subject: "Notes from the product sync + next steps",
    body:
      "<p>Thanks everyone for the sync today. Quick recap of decisions:</p><ul><li>Ship the onboarding tour behind a flag</li><li>Defer the admin dashboard to next cycle</li><li>Priya owns the pricing redesign</li><li>Demo to leadership on Friday</li></ul><p>Action items are in the doc. Ping me if I missed anything.</p><p>Sofia</p>",
    snippet: "Thanks everyone for the sync today. Quick recap: ship onboarding tour behind a flag, defer admin dashboard.",
    date: iso(3 * DAY),
    isRead: true,
    isStarred: true,
    isImportant: false,
    folder: "INBOX",
    labels: "Work",
    hasAttachment: false,
    attachmentName: "",
  },
  {
    threadId: "t_tax10",
    fromName: "City Tax Office",
    fromEmail: "no-reply@citytax.gov",
    toEmails: me,
    ccEmails: "",
    bccEmails: "",
    subject: "Reminder: property tax payment due Sep 30",
    body:
      "<p>This is a friendly reminder that your annual property tax payment is due on September 30.</p><p>You can pay online at citytax.gov/pay using your account number on the bill.</p><p>Thank you,<br/>City Tax Office</p>",
    snippet: "This is a friendly reminder that your annual property tax payment is due on September 30.",
    date: iso(4 * DAY),
    isRead: true,
    isStarred: false,
    isImportant: false,
    folder: "INBOX",
    labels: "Finance",
    hasAttachment: true,
    attachmentName: "property-tax-bill.pdf",
  },
  {
    threadId: "t_code11",
    fromName: "GitHub",
    fromEmail: "notifications@github.com",
    toEmails: me,
    ccEmails: "",
    bccEmails: "",
    subject: "[frostedlabs/web] @you were mentioned in #482",
    body:
      "<p><b>marcus</b> mentioned you in frostedlabs/web#482:</p><blockquote>Can @you take a look at the SSR hydration warnings on /pricing? I think the theme provider is causing a mismatch on first paint.</blockquote><p>View the issue on GitHub.</p>",
    snippet: "marcus mentioned you in frostedlabs/web#482 — can you look at the SSR hydration warnings on /pricing?",
    date: iso(4 * DAY + 4 * HOUR),
    isRead: true,
    isStarred: false,
    isImportant: false,
    folder: "INBOX",
    labels: "",
    hasAttachment: false,
    attachmentName: "",
  },
  {
    threadId: "t_book12",
    fromName: "GoodReads",
    fromEmail: "updates@goodreads.com",
    toEmails: me,
    ccEmails: "",
    bccEmails: "",
    subject: "Your 2025 Reading Challenge: you're 4 books ahead of schedule 📚",
    body:
      "<p>Nice work! You've finished 28 of 30 books this year. Here are three picks we think you'll love next:</p><ul><li>The Midnight Library</li><li>Project Hail Mary</li><li>The Invisible Life of Addie LaRue</li></ul><p>Keep turning those pages.</p>",
    snippet: "Nice work! You've finished 28 of 30 books this year. Three picks we think you'll love next.",
    date: iso(5 * DAY),
    isRead: true,
    isStarred: false,
    isImportant: false,
    folder: "INBOX",
    labels: "Social",
    hasAttachment: false,
    attachmentName: "",
  },
  {
    threadId: "t_offer13",
    fromName: "Jenny Park",
    fromEmail: "jenny@talentbridge.co",
    toEmails: me,
    ccEmails: "",
    bccEmails: "",
    subject: "Following up on the senior role — quick chat next week?",
    body:
      "<p>Hi,</p><p>It was great speaking last week! The team was really impressed with your portfolio, especially the design-system work.</p><p>Would you have 30 minutes next Tuesday or Wednesday for a follow-up chat with the engineering lead? Send over a couple of windows that work and I'll lock it in.</p><p>Best,<br/>Jenny</p>",
    snippet: "The team was really impressed with your portfolio. Would you have 30 min next week for a follow-up chat?",
    date: iso(6 * DAY),
    isRead: true,
    isStarred: true,
    isImportant: true,
    folder: "INBOX",
    labels: "Personal,Work",
    hasAttachment: false,
    attachmentName: "",
  },
  // Spam
  {
    threadId: "t_spam1",
    fromName: "Mega Lotto Winner",
    fromEmail: "claim@mega-lotto-prize.win",
    toEmails: me,
    ccEmails: "",
    bccEmails: "",
    subject: "CONGRATULATIONS! You've won $1,000,000 — claim now",
    body:
      "<p>Dear lucky winner,</p><p>You have been selected as the grand prize winner of our international lottery. To claim your $1,000,000 prize, please send your bank details and a processing fee of $250 within 24 hours.</p><p>This is definitely not a scam.</p>",
    snippet: "You have been selected as the grand prize winner. Send your bank details and a $250 processing fee.",
    date: iso(3 * DAY),
    isRead: false,
    isStarred: false,
    isImportant: false,
    folder: "SPAM",
    labels: "",
    hasAttachment: false,
    attachmentName: "",
  },
  {
    threadId: "t_spam2",
    fromName: "CryptoMoon Now",
    fromEmail: "launch@cryptomoon-now.io",
    toEmails: me,
    ccEmails: "",
    bccEmails: "",
    subject: "🚀 1000x moonshot launching TODAY — get in early",
    body:
      "<p>Don't miss out on the next big thing. Our token has done a 50x in private beta and is launching to the public today. Send ETH now to receive 10x airdrop.</p>",
    snippet: "Don't miss out on the next big thing. Our token has done a 50x in private beta.",
    date: iso(7 * DAY),
    isRead: false,
    isStarred: false,
    isImportant: false,
    folder: "SPAM",
    labels: "",
    hasAttachment: false,
    attachmentName: "",
  },
  // Trash
  {
    threadId: "t_trash1",
    fromName: "StorePromo",
    fromEmail: "deals@storepromo.shop",
    toEmails: me,
    ccEmails: "",
    bccEmails: "",
    subject: "Last chance: 70% off everything ends tonight",
    body: "<p>Last chance to grab 70% off everything. Use code BYE70 at checkout.</p>",
    snippet: "Last chance to grab 70% off everything. Use code BYE70 at checkout.",
    date: iso(8 * DAY),
    isRead: true,
    isStarred: false,
    isImportant: false,
    folder: "TRASH",
    labels: "",
    hasAttachment: false,
    attachmentName: "",
  },
  // Sent
  {
    threadId: "t_design2",
    fromName: "You",
    fromEmail: me,
    toEmails: "priya.sharma@northwind.design",
    ccEmails: "mark@northwind.design",
    bccEmails: "",
    subject: "Re: Q3 product redesign — final mockups attached",
    body:
      "<p>Hey Priya,</p><p>These look fantastic — the rose CTA really pops. Two tiny things:</p><ul><li>Can we bump the testimonial avatar size from 32 to 40?</li><li>The mobile pricing tabs need an active state — currently it's hard to tell which is selected.</li></ul><p>Otherwise, ship it. See you at 3.</p><p>Thanks!</p>",
    snippet: "These look fantastic — the rose CTA really pops. Two tiny things on the testimonials and mobile tabs.",
    date: iso(4 * HOUR),
    isRead: true,
    isStarred: false,
    isImportant: false,
    folder: "SENT",
    labels: "Work",
    hasAttachment: false,
    attachmentName: "",
  },
  {
    threadId: "t_sent1",
    fromName: "You",
    fromEmail: me,
    toEmails: "dana.w@gmail.com",
    ccEmails: "",
    bccEmails: "",
    subject: "Re: BBQ at ours this Saturday? 🍔",
    body:
      "<p>Dana!</p><p>Yes! We'll be there around 4. I'll bring a potato salad. Should I bring drinks too?</p><p>See you Saturday 🎉</p>",
    snippet: "Yes! We'll be there around 4. I'll bring a potato salad. Should I bring drinks too?",
    date: iso(1 * DAY + 2 * HOUR),
    isRead: true,
    isStarred: false,
    isImportant: false,
    folder: "SENT",
    labels: "Personal,Social",
    hasAttachment: false,
    attachmentName: "",
  },
  {
    threadId: "t_sent2",
    fromName: "You",
    fromEmail: me,
    toEmails: "jenny@talentbridge.co",
    ccEmails: "",
    bccEmails: "",
    subject: "Re: Following up on the senior role — quick chat next week?",
    body:
      "<p>Hi Jenny,</p><p>Thanks so much — I'd love to chat with the engineering lead. Tuesday afternoon works great. Would 2pm your time work? Happy to do Wednesday morning too if that's easier.</p><p>Looking forward to it!</p>",
    snippet: "Thanks so much — I'd love to chat. Tuesday afternoon works great, would 2pm your time work?",
    date: iso(5 * DAY + 2 * HOUR),
    isRead: true,
    isStarred: false,
    isImportant: false,
    folder: "SENT",
    labels: "Personal,Work",
    hasAttachment: false,
    attachmentName: "",
  },
  // Drafts
  {
    threadId: "t_draft1",
    fromName: "You",
    fromEmail: me,
    toEmails: "sofia@northwind.design",
    ccEmails: "",
    bccEmails: "",
    subject: "Re: Notes from the product sync + next steps",
    body:
      "<p>Hi Sofia,</p><p>Thanks for the recap. On the onboarding tour — should we gate it behind the flag <i>only</i> for new signups, or also for returning users who haven't completed their profile? Leaning toward the latter but want to make sure we don't </p>",
    snippet: "Thanks for the recap. On the onboarding tour — should we gate it behind the flag only for new signups...",
    date: iso(2 * HOUR),
    isRead: true,
    isStarred: false,
    isImportant: false,
    folder: "DRAFTS",
    labels: "Work",
    hasAttachment: false,
    attachmentName: "",
  },
];
